create table HOTEL(
 HNO NUMBER(3) PRIMARY KEY,
 NAME VARCHAR2(30),
 ADDRESS VARCHAR2(20)
);



insert INTO hotel (HNO, NAME, ADDRESS)
VALUES (1, 'SEA HAWKS', 'MUMBAI');

insert INTO hotel (HNO, NAME, ADDRESS)
VALUES (3, 'GREEN VIEW', 'Kolkata');

insert INTO hotel (HNO, NAME, ADDRESS)
VALUES (4, 'SUNSHINE', 'Delhi');


insert INTO hotel (HNO, NAME, ADDRESS)
VALUES (2, 'SAGAR SANGAM', 'Chennai');

insert INTO hotel (HNO, NAME, ADDRESS)

VALUES (5,'TJ' , 'KOLKATA');


UPDATE HOTEL 
set ADDRESS = 'Kolkata'
where HNO=5


SELECT   *
FROM HOTEL



/* creating table room */

CREATE TABLE  ROOM (
RNO NUMBER(5) PRIMARY KEY,
RTYPE VARCHAR2(20),
HNO NUMBER(3)  REFERENCEs HOTEL(HNO),  --AFTER CHANGE
PRICE NUMBER(5) CHECK (PRICE>500)
);

INSERT ALL
--INTO ROOM (RNO ,RTYPE, HNO ,PRICE) VALUES (1,'3BEDNONAC',1,1000)
INTO ROOM (RNO ,RTYPE, HNO,PRICE) VALUES (2,'3BEDAC',2,1600)
INTO ROOM (RNO ,RTYPE, HNO ,PRICE) VALUES (3,'2BEDAC',3,1500)
INTO ROOM (RNO ,RTYPE, HNO ,PRICE) VALUES (4,'2BEDNONAC',4,900)
INTO ROOM (RNO ,RTYPE, HNO ,PRICE) VALUES (5,'3BEDAC',5,1600)
INTO ROOM (RNO ,RTYPE, HNO ,PRICE) VALUES (6,'2BEDAC',5,1300)
SELECT * 
FROM ROOM


INSERT 
INTO ROOM (RNO ,RTYPE, HNO ,PRICE) VALUES (1,'3BEDNONAC',1,1000)

ALTER TABLE ROOM
RENAME COLUMN  HN0 TO HNO


/*   table for guest       */

create table GUEST( 
GNO  NUMBER(6) PRIMARY KEY,
GNAME VARCHAR2(30),
GADDRESS VARCHAR2(30)
);




INSERT ALL
INTO GUEST (GNO, GNAME,GADDRESS ) VALUES( 1,'Akash' , 'ABC')
INTO GUEST (GNO, GNAME,GADDRESS ) VALUES( 2,'Sagar' , 'DEF')
INTO GUEST (GNO, GNAME,GADDRESS ) VALUES( 3,'Nabdi' , 'GHI')
INTO GUEST (GNO, GNAME,GADDRESS ) VALUES( 4,'Tusar' , 'JKL')
INTO GUEST (GNO, GNAME,GADDRESS ) VALUES( 5,'Giri' , 'MNO')
INTO GUEST (GNO, GNAME,GADDRESS ) VALUES( 6,'Mihir' , 'PQR')
SELECT * 
FROM guest

DROP TABLE GUEST

/* table for booking      */

create table BOOKING ( 
HNO  NUMBER(4) references HOTEL(HNO),
GNO NUMBER(6)  REFERENCES GUEST(GNO),
RNO NUMBER(5)  REFERENCES ROOM(RNO)
);

INSERT ALL
INTO BOOKING ( HNO,GNO, RNO )  VALUES (1,1,3)
INTO BOOKING ( HNO,GNO, RNO )  VALUES (2,2,1) 
INTO BOOKING ( HNO,GNO, RNO )  VALUES (3,3,2)
INTO BOOKING ( HNO,GNO, RNO )  VALUES (4,4,5)
INTO BOOKING ( HNO,GNO, RNO )  VALUES (5,5,1)
INTO BOOKING ( HNO,GNO, RNO )  VALUES (5,6,2)

SELECT * FROM  booking



DROP TABLE BOOKING

/*
   diy on table
*/


SELECT COUNT(HNO)   
FROM  HOTEL



------ querey---
QUERIES 1

SELECT GNAME
FROM GUEST
WHERE GNO IN (SELECT GNO
FROM BOOKING
where  HNO  in(select HNO
from hotel 
where address = 'Kolkata' OR  address= 'Chennai'))


----QURIES 2

SELECT COUNT(GNO) AS TOTAL_GUEST
FROM BOOKING 
WHERE HNO   =(SELECT  HNO
FROM HOTEL
WHERE  NAME = 'TJ')

---QUERIEY 3
SELECT HNO ,SUM (RNO) AS TOTAL_ROOM
FROM ROOM
GROUP BY HNO;

SELECT *
FROM ROOM




---QUERIY 4   1

ALTER TABLE BOOKING 
ADD DATE_FROM DATE;

ALTER TABLE BOOKING 
ADD DATE_TO  DATE;


---QUERIY 4 2

SELECT *
FROM BOOKING

DELETE FROM BOOKING WHERE HNO=5 

---QUERY 4 3
SELECT * 
FROM GUEST 

UPDATE GUEST
SET GADDRESS = 'XYZ'
WHERE GNO = 3



---QUERY 4.4

DROP TABLE HOTEL
DROP TABLE ROOM
DROP TABLE GUEST 
DROP TABLE BOOKING