// if (true) {
//   console.log('I am insde if block');
//    colse.log(' i am still inside code block')
// }
//    else {    


//    } 

//  var  whoIsHere = 'coder'

//  if (whoIsHere === 'user') {
//        console.log('gretting for user  ')
//        console.log('Allow acess to view all course ')
//  } else if  (whoIsHere === 'teacher'){
//       console.log('Greeting massage for teacher')
//       console.log('allow acess to his  corses')
// } else {  
//       console.log('MASSAGE : PLEASE VERIFY YORE EMAIL')
//       console.log('Send user an email for verification')
     
// }

//  student grade 

let  marks = 8


   if ( marks >=9) {
          console.log('very good ')
      }else if (marks <9 & marks >5){
            console.log('good')
      }else {
           console.log('work hard') 
      }

